sn_provider_vk:
  path:     /vk
  defaults: { _controller: SnDataProviderBundle:Default:vk }

sn_provider_telegram:
  path:     /telegram
  defaults: { _controller: SnDataProviderBundle:Default:telegram }

sn_provider_facebook:
  path:     /facebook
  defaults: { _controller: SnDataProviderBundle:Default:facebook }